import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';
import './globals.css';
import { ColorSchemeScript } from '@mantine/core';

import '@mantine/core/styles.css';
import dynamic from 'next/dynamic';
import { MantineProvider } from '@mantine/core';
import theme from '@/styles/theme';
import { ModalProvider } from '@/providers';
import { ModalManager } from '@/components/modals';

const RatedMoviesProvider = dynamic(
  () => import('@/providers').then((mod) => mod.RatedMoviesProvider),
  {
    ssr: false,
  }
);

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Startup Summer 2024',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <MantineProvider theme={theme}>
          <RatedMoviesProvider>
            <ModalProvider>
              <ModalManager />
              {children}
            </ModalProvider>
          </RatedMoviesProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
