import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';
import './globals.css';
import { ColorSchemeScript } from '@mantine/core';

import '@mantine/core/styles.css';
import { MantinProvider } from '@/providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Startup Summer 2024',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <MantinProvider>{children}</MantinProvider>
      </body>
    </html>
  );
}

// import Link from 'next/link';
// import { Button } from '@mantine/core';

// function Demo() {
//   return (
//     <Button component={Link} href="/hello">
//       Next link button
//     </Button>
//   );
// }
